### ISSUE TITLE
Allow creating lists of project members

### ISSUE THREAD

**Issue by mcescalante** [OpenHumans/oh-proj-management#39]
We would like to allow lists/groups of project members to be added to this application. The administrator should be able to create these groups and add members to those groups.

The list/group data should be held in a model, something like `ProjectGroup`, which would allow many project members to be manually added by a project administrator after the group was created. These member lists will only be in this `oh-proj-management` application; these lists will not be sent back to the main Open Humans site. There should be a screen to display these groups of users, with some basic detail on each user.

## Acceptance criteria

- Adds a model for member lists / groups like `ProjectGroup`
- View that allows an administrator to create a (named) group and add members to that group
- View that displays all lists/groups with the users in each list/group

**Comment by shubhangi-chauhan** [comment]
On it! :)

**Comment by shubhangi-chauhan** [comment]
Since we don't store the members in the database, we can't use relationships in the `members` field of the proposed `ProjectGroup` table.
I see a couple of options.
- Storing member IDs (OpenHumans ID) in CSV format. In this case, the `ProjectGroup` table will have a `members` text field which will store the IDs.
- Creating a `Member` table which will store the members' group and any more details that might get added later, say notes from https://github.com/OpenHumans/oh-proj-management/issues/40 using appropriate relationships.

Which one should I go with?

**Comment by gedankenstuecke** [comment]
This should be the latter, having a `Member` model which stores the `project_member_id`, potentially along with meta data about these members.
